apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::854682238426:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EHNWA7F63CFJ
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::854682238426:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-20T12:32:28Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2020-12-20T12:32:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1354"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2b0076c0-950f-450a-8d97-4b1da659e7b9
