apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::854682238426:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RWWUJJYST8IN
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-19T17:36:32Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2020-12-19T17:36:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1343"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5e1f21f4-70c2-4644-a105-a669f438ff74
